### ISSUE TITLE
Is it possible Mirage causes the font glitch but in P7?

### ISSUE THREAD

**Issue by macta** [juliendelplanque/WindowsPreviewer#18] opened 2019-03-18 16:04 UTC
Lots of people are reporting a font glitch issue in Pharo - and it really is noticable in P7 where suddenly characters will be garbled on the screen. This seems to magnify when using Mirage - where I seem to get it every few minutes when Mirage is loaded in a small image (I am loading into OSX 64bit, 7.0.2) - then I load the dev version and then finally my Exercism project (also quite small - but it does drag in Mocketry).

As Mirage, does have an option to refresh thumbnails every x seconds - I wonder if this might exacperate this problem somehow?

I mention this in case it rings any bells.

The workaround is to save your image (or tick/untick trutype fonts in settings) - and this use to be a one off without Mirage loaded, but I find I have to save every 10-20 mins to cure it. (this is empirical, and needs more exploration)

**Comment by macta** [comment] 2019-03-20 11:15
I'm not sure - in a fresh image with mirage, it now seems to happen less frequently (however - It still keeps coming back, whereas I swear my previous fresh images didn't get the font glitch after an initial save). Still monitoring - but curious if anyone else notices this now too.

**Comment by juliendelplanque** [comment] 2019-04-10 14:03
Hello,

Indeed, Mirage magnify the bug.

We discussed that at Pharo days and Pablo investigated this. Actually, he just told me today that he think et found the cause of the bug using Mirage. Which is nice.

He will propose a solution as a PR on Pharo repository. :-)

So I close this issue since the bug is in Pharo.

Cheers,

Julien

**Closed as completed by juliendelplanque** 2019-04-10 14:03 UTC

**Comment by macta** [comment] 2019-04-10 18:34
Yes - a nice outcome
